version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mentor-connect-app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - mentor-network
    volumes:
      - app_logs:/app/logs

  postgres:
    image: postgres:15-alpine
    container_name: mentor-connect-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-mentor_connect}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mentor-network

  redis:
    image: redis:7-alpine
    container_name: mentor-connect-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mentor-network

  nginx:
    image: nginx:alpine
    container_name: mentor-connect-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - mentor-network

networks:
  mentor-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  app_logs:
