version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
      - ./seed.sh:/docker-entrypoint-initdb.d/seed.sh:ro
      - ./mock-data:/docker-entrypoint-initdb.d/mock-data:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MOCK_INTEGRATIONS: ${MOCK_INTEGRATIONS}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - "${API_PORT:-5000}:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=5000
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - PLATFORM_EMAIL=${PLATFORM_EMAIL}
      - ZOOM_API_KEY=${ZOOM_API_KEY}
      - ZOOM_API_SECRET=${ZOOM_API_SECRET}
      - ZOOM_VERIFICATION_TOKEN=${ZOOM_VERIFICATION_TOKEN}
      - ZOOM_WEBHOOK_SECRET=${ZOOM_WEBHOOK_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - PLATFORM_FEE_PERCENT=${PLATFORM_FEE_PERCENT}
      - REFERRAL_REWARD_AMOUNT=${REFERRAL_REWARD_AMOUNT}
      - MOCK_INTEGRATIONS=${MOCK_INTEGRATIONS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - REACT_APP_API_URL=/api  # Changed from ${REACT_APP_API_URL}
        - REACT_APP_STRIPE_PUBLIC_KEY=${REACT_APP_STRIPE_PUBLIC_KEY}
    restart: always
    ports:
      - "3001"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
    - REACT_APP_DOCKER=true

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge